#
# Jenkins pipeline for CNaaS
#

disabled: false

# downstream:
#   - cnaas-httpd
#   - cnaas-dhcpd
#   - cnaas-api
#   - cnaas-postgres

git:
  branch: develop
  extensions:
    shallow_clone: true

script:
  - "ssh root@puckly.sunet.se /root/starttests.sh ${GIT_BRANCH}"
  # - "python3.7 -m venv venv"
  # - ". venv/bin/activate"
  # - "pip install --upgrade setuptools pip wheel mypy"
  # - "pip install --index-url https://pypi.sunet.se -r requirements.txt"
  # - "nosetests --with-xunit"

slack:
  room: "cnaas-builds"

extra_jobs:
  - name: cnaas-dhcpd
    git:
      branch: develop
    builders:
      - docker
    docker_name: cnaas/dhcpd
    docker_context_dir: docker/dhcpd
    docker_tags:
      - "v1.0"

  - name: cnaas-api
    git:
      branch: develop
    builders:
      - docker
    docker_name: cnaas/api
    docker_context_dir: docker/api
    docker_tags:
      - "v1.4"
      - "develop"

  - name: cnaas-api-master
    git:
      branch: master
    builders:
      - docker
    docker_name: cnaas/api
    docker_context_dir: docker/api
    docker_tags:
      - "v1.3"
      - "master"

  - name: cnaas-postgres
    git:
      branch: develop
    builders:
      - docker
    docker_name: cnaas/postgres
    docker_context_dir: docker/postgres
    docker_tags:
      - "v1.0"
