repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: "(docker/.*patch)"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff
        pass_filenames: false
        args: [./]
      - id: ruff-format
        pass_filenames: false
        args: [--check, ./]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: "mypy"
        types: [python]
        require_serial: true
        verbose: true
        args:
          - --no-warn-incomplete-stub
          - --ignore-missing-imports
          - --no-warn-unused-ignores
          - --allow-untyped-decorators
          - --no-namespace-packages
          - --allow-untyped-globals
          - --check-untyped-defs
        exclude: "(alembic/.*)|(.*test.*)|(docker/.*)"
