"""add config hash for devices

Revision ID: 1327fb92d384
Revises: d1e7569c57a2
Create Date: 2019-05-23 08:40:31.711177

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1327fb92d384"
down_revision = "a3f3bc390462"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("device", sa.Column("confhash", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("device", "confhash")
    # ### end Alembic commands ###
