"""Add infra IPv6 address field to Device

Revision ID: 2776e92f7b02
Revises: adcce7d9baaa
Create Date: 2023-03-17 15:26:18.242019

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '2776e92f7b02'
down_revision = 'adcce7d9baaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('infra_ipv6', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'infra_ipv6')
    # ### end Alembic commands ###
