"""Add IPv6 address fields to linknets

Revision ID: 4ec3a80231f8
Revises: b7629362583c
Create Date: 2023-03-10 15:45:27.507737

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '4ec3a80231f8'
down_revision = 'b7629362583c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linknet', sa.Column('ipv6_network', sa.Unicode(length=43), nullable=True))
    op.add_column('linknet', sa.Column('device_a_ipv6', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True))
    op.add_column('linknet', sa.Column('device_b_ipv6', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linknet', 'device_b_ipv6')
    op.drop_column('linknet', 'device_a_ipv6')
    op.drop_column('linknet', 'ipv6_network')
    # ### end Alembic commands ###
