"""save change_score in separate column instead of putting it amongst devices in result to make things cleaner.

Revision ID: 5aa2593e147a
Revises: 65b83c197420
Create Date: 2019-12-05 13:10:39.311902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5aa2593e147a"
down_revision = "65b83c197420"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job", sa.Column("change_score", sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "change_score")
    # ### end Alembic commands ###
