"""Added port field.

Revision ID: 6627b128bd5c
Revises: 922589188efe
Create Date: 2019-08-29 14:36:32.125191

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6627b128bd5c"
# down_revision = '922589188efe'
down_revision = "6c6bec879fa8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("device", sa.Column("port", sa.Integer()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("device", "port")
    # ### end Alembic commands ###
