"""add permission tables

Revision ID: 7bd40f19727f
Revises: 3dcd43eda3de
Create Date: 2026-01-16 09:28:18.096190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bd40f19727f'
down_revision = '3dcd43eda3de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Unicode(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attribute_name', sa.Unicode(length=255), nullable=False),
    sa.Column('attribute_value', sa.Unicode(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('last_modified_by', sa.Unicode(length=255), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_role_mappings_attribute', 'role_mappings', ['attribute_name', 'attribute_value'], unique=False)
    op.create_index('ix_role_mappings_role_id', 'role_mappings', ['role_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Unicode(length=1024), nullable=True),
    sa.Column('methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('endpoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exclude_endpoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_modified_by', sa.Unicode(length=255), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_role_permissions_role_id', 'role_permissions', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_permissions_role_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_role_mappings_role_id', table_name='role_mappings')
    op.drop_index('ix_role_mappings_attribute', table_name='role_mappings')
    op.drop_table('role_mappings')
    op.drop_table('roles')
    # ### end Alembic commands ###
