"""alembic start

Revision ID: a3f3bc390462
Revises: base
Create Date: 2019-05-14 09:12:15.785952

"""
# revision identifiers, used by Alembic.
revision = "a3f3bc390462"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###