"""alembic start

Revision ID: a3f3bc390462
Revises:
Create Date: 2019-05-14 09:12:15.785952

"""
import sqlalchemy as sa

from alembic import op
import os

# revision identifiers, used by Alembic.
revision = "a3f3bc390462"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    # migrations_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)))
    with open(os.path.join("/mnt/c/Github/cnaas-nms/docker/postgres/nms.sql")) as f:
            data = f.read()
            conn.execute(sa.text(data))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
