"""Make ReserveIP IP unique

Revision ID: c1e5bd25c3a1
Revises: 7bd40f19727f
Create Date: 2026-06-15 07:46:51.390231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e5bd25c3a1'
down_revision = '7bd40f19727f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reservedip', ['ip'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservedip', type_='unique')
    # ### end Alembic commands ###
