"""add_cpu_arch_to_device

Revision ID: e668b1485836
Revises: c1e5bd25c3a1
Create Date: 2026-08-27 11:26:32.112984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e668b1485836'
down_revision = 'c1e5bd25c3a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    cpuarchitecture = sa.Enum('X86_32', 'X86_64', 'ARM64', name='cpuarchitecture')
    cpuarchitecture.create(op.get_bind(), checkfirst=True)
    op.add_column('device', sa.Column('cpu_arch', sa.Enum('X86_32', 'X86_64', 'ARM64', name='cpuarchitecture'), nullable=True))
    op.create_index(op.f('ix_interface_device_id'), 'interface', ['device_id'], unique=False)
    op.drop_constraint('device_a_uq', 'linknet', type_='unique')
    op.drop_constraint('device_b_uq', 'linknet', type_='unique')
    op.create_unique_constraint(None, 'linknet', ['device_b_id', 'device_b_port'])
    op.create_unique_constraint(None, 'linknet', ['device_a_id', 'device_a_port'])
    op.create_unique_constraint(None, 'mgmtdomain', ['device_a_id', 'device_b_id'])
    op.alter_column('site', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'mgmtdomain', type_='unique')
    op.drop_constraint(None, 'linknet', type_='unique')
    op.drop_constraint(None, 'linknet', type_='unique')
    op.create_unique_constraint('device_b_uq', 'linknet', ['device_b_id', 'device_b_ip'])
    op.create_unique_constraint('device_a_uq', 'linknet', ['device_a_id', 'device_a_ip'])
    op.drop_index(op.f('ix_interface_device_id'), table_name='interface')
    op.drop_column('device', 'cpu_arch')
    sa.Enum(name='cpuarchitecture').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
