services:

  #
  # CNaaS service dependencies
  #

  cnaas_postgres:
    image: cnaas-postgres-test
    build:
      context: ./postgres/
      args:
        - SQLFILE=nms_test.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cnaas
      - POSTGRES_PASSWORD=cnaas
      - POSTGRES_DB=cnaas

  cnaas_redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
