name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ruff:
    name: Ruff linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dev dependencies from pyproject
        run: |
          pip install --upgrade pip
          pip install --group dev

      - name: Run ruff check
        run: ruff check ./

      - name: Run ruff format check
        run: ruff format --check src/
        run: ruff format --check ./


  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dev dependencies from pyproject
        run: |
          pip install --upgrade pip
          pip install --group dev

      - name: Run mypy
        run: pre-commit run mypy --all-files
